### ISSUE TITLE
Catalogue

### ISSUE THREAD

**Issue by BarbzYHOOL** [skxawng-cu/mod-tele-new-players#4]
Hey, if this module is working fine, you could submit it to our catalogue (I haven't tried it yet)

**Comment by skxawng-cu** [comment]
It's works, I am using it in a PvP ream in my server but I don't know how to submit it. Can you explain me?

**Comment by BarbzYHOOL** [comment]
http://www.azerothcore.org/catalogue/ click on the right

**Comment by skxawng-cu** [comment]
I already submit the module to the cataloge. I don't know if I did it right, you can check it out.
